import {
  Building,
  CalendarEvent,
  Contractor,
  ServiceCategory,
  Ticket,
  User,
  WorkOrder,
} from "@/types/types";

export const users: User[] = [
  {
    id: "user1",
    name: "Patricia Walker",
    email: "hallrichard@ewing.biz",
    phone: "5218339801",
    buildingId: "b1",
    avatar: require("../assets/images/user-avatar.png"),
  },
  {
    id: "user2",
    name: "Robert Moses",
    email: "mcconnellveronica@thompson-phillips.com",
    phone: "(713)873-6246",
    buildingId: "b2",
    avatar: require("../assets/images/user-avatar.png"),
  },
  {
    id: "user3",
    name: "Alice Garcia",
    email: "david62@williams.com",
    phone: "286-711-6511x986",
    buildingId: "b3",
    avatar: require("../assets/images/user-avatar.png"),
  },
  {
    id: "user4",
    name: "April Rice",
    email: "chartman@hotmail.com",
    phone: "001-149-710-2715x091",
    buildingId: "b4",
    avatar: require("../assets/images/user-avatar.png"),
  },
  {
    id: "user5",
    name: "Cameron Miller",
    email: "jessica22@hotmail.com",
    phone: "+1-873-840-6240x61832",
    buildingId: "b5",
    avatar: require("../assets/images/user-avatar.png"),
  },
];

export const contractors: Contractor[] = [
  {
    id: "contractor1",
    name: "Maria Hubbard",
    skills: ["HVAC", "Cleaning"],
    isAvailable: true,
    avatar: require("../assets/images/contractor.png"),
    phone: "+1-792-382-8593x4752",
    email: "kevin00@jimenez.com",
    rating: 3.5,
  },
  {
    id: "contractor2",
    name: "Alex Noble",
    skills: ["HVAC"],
    isAvailable: true,
    avatar: require("../assets/images/contractor.png"),
    phone: "538-702-1431",
    email: "starkcarl@escobar.com",
    rating: 3.6,
  },
  {
    id: "contractor3",
    name: "Larry Pugh",
    skills: ["Plumbing", "HVAC", "Cleaning"],
    isAvailable: true,
    avatar: require("../assets/images/contractor.png"),
    phone: "5429408642",
    email: "danielbates@lowery.com",
    rating: 4.2,
  },
  {
    id: "contractor4",
    name: "Jodi Kelley",
    skills: ["HVAC", "Pest Control"],
    isAvailable: false,
    avatar: require("../assets/images/contractor.png"),
    phone: "1064117118",
    email: "joshuaflores@hotmail.com",
    rating: 4.3,
  },
  {
    id: "contractor5",
    name: "Timothy Miller",
    skills: ["Cleaning"],
    isAvailable: true,
    avatar: require("../assets/images/contractor.png"),
    phone: "152-385-5000x9186",
    email: "houstondonna@hotmail.com",
    rating: 4.4,
  },
];

export const services: ServiceCategory[] = [
  {
    id: "s1",
    name: "Plumbing",
    icon: require("../assets/images/icons8-plumbing-50.png"),
  },
  {
    id: "s2",
    name: "Electrical",
    icon: require("../assets/images/icons8-electrical-50.png"),
  },
  {
    id: "s3",
    name: "Cleaning",
    icon: require("../assets/images/icons8-cleaning-50.png"),
  },

  {
    id: "s4",
    name: "HVAC",
    icon: require("../assets/images/icons8-smart-ac-24.png"),
  },
  {
    id: "s5",
    name: "Pest Control",
    icon: require("../assets/images/icons8-pest-control-64.png"),
  },
];

export const workOrders: WorkOrder[] = [
  {
    id: "wo1",
    title: "Concern oil pull book.",
    type: "Electrical",
    status: "Completed",
    assignedTo: "contractor4",
    requestedBy: "user5",
    date: "2025-06-03",
    time: "09:18 AM",
  },
  {
    id: "wo2",
    title: "Result article improve.",
    type: "Cleaning",
    status: "Pending",
    assignedTo: "contractor3",
    requestedBy: "user5",
    date: "2025-06-02",
    time: "07:14 PM",
  },
  {
    id: "wo3",
    title: "Total own mind.",
    type: "Plumbing",
    status: "Completed",
    assignedTo: "contractor2",
    requestedBy: "user4",
    date: "2025-06-01",
    time: "07:46 PM",
  },
  {
    id: "wo4",
    title: "Age surface seem.",
    type: "Cleaning",
    status: "Rejected",
    assignedTo: "contractor2",
    requestedBy: "user3",
    date: "2025-06-03",
    time: "11:25 PM",
  },
  {
    id: "wo5",
    title: "Month skill.",
    type: "Plumbing",
    status: "Pending",
    assignedTo: "contractor2",
    requestedBy: "user5",
    date: "2025-06-03",
    time: "08:12 PM",
  },
  {
    id: "wo6",
    title: "House hair knowledge",
    type: "Cleaning",
    status: "Completed",
    assignedTo: "contractor1",
    requestedBy: "user1",
    date: "2025-06-09",
    time: "03:50 AM",
  },
  {
    id: "wo7",
    title: "Offer professor reveal",
    type: "Cleaning",
    status: "Rejected",
    assignedTo: "contractor2",
    requestedBy: "user1",
    date: "2025-06-05",
    time: "08:52 PM",
  },
  {
    id: "wo8",
    title: "System what",
    type: "Plumbing",
    status: "In Progress",
    assignedTo: "contractor1",
    requestedBy: "user1",
    date: "2025-06-11",
    time: "04:46 AM",
  },
  {
    id: "wo9",
    title: "Consumer democratic",
    type: "Cleaning",
    status: "Pending",
    assignedTo: "contractor1",
    requestedBy: "user1",
    date: "2025-06-08",
    time: "10:07 AM",
  },
  {
    id: "wo10",
    title: "Performance station",
    type: "Electrical",
    status: "In Progress",
    assignedTo: "contractor4",
    requestedBy: "user1",
    date: "2025-06-07",
    time: "10:14 AM",
  },
  {
    id: "wo11",
    title: "Speech idea",
    type: "Electrical",
    status: "Pending",
    assignedTo: "contractor2",
    requestedBy: "user1",
    date: "2025-06-05",
    time: "08:32 AM",
  },
  {
    id: "wo12",
    title: "Change weight others",
    type: "Cleaning",
    status: "Pending",
    assignedTo: "contractor2",
    requestedBy: "user1",
    date: "2025-06-07",
    time: "02:26 PM",
  },
];

export const tickets: Ticket[] = [
  {
    id: "t1",
    title: "Test under pass before.",
    createdBy: "user4",
    createdAt: "2025-06-01T04:49:21",
    status: "New",
  },
  {
    id: "t2",
    title: "Physical million hour.",
    createdBy: "user4",
    createdAt: "2025-06-01T07:13:24",
    status: "Resolved",
  },
  {
    id: "t3",
    title: "Position card.",
    createdBy: "user3",
    createdAt: "2025-06-01T03:58:36",
    status: "New",
  },
];

export const calendarEvents: CalendarEvent[] = [
  {
    id: "ce1",
    serviceType: "Plumbing",
    contractorId: "contractor2",
    date: "2025-06-02",
    time: "01:08 AM",
    status: "Upcoming",
  },
  {
    id: "ce2",
    serviceType: "Cleaning",
    contractorId: "contractor3",
    date: "2025-06-01",
    time: "04:01 PM",
    status: "Completed",
  },
];

export const buildings: Building[] = [
  {
    id: "b1",
    name: "Roosevelt Plaza",
    location: "San Francisco, CA",
    openWorkOrders: 2,
    completedWorkOrders: 5,
  },
  {
    id: "b2",
    name: "Stevenson Court",
    location: "Los Angeles, CA",
    openWorkOrders: 1,
    completedWorkOrders: 6,
  },
  {
    id: "b3",
    name: "Lincoln Towers",
    location: "New York, NY",
    openWorkOrders: 3,
    completedWorkOrders: 4,
  },
  {
    id: "b4",
    name: "Washington Heights",
    location: "Chicago, IL",
    openWorkOrders: 0,
    completedWorkOrders: 8,
  },
  {
    id: "b5",
    name: "Jefferson Apartments",
    location: "Houston, TX",
    openWorkOrders: 1,
    completedWorkOrders: 3,
  },
];
